### PR TITLE
Add Apache license and make it clear that contributions are Apache 2.

### PR DESCRIPTION
**Pull request by tetron**

### CODE REVIEW

**Comment by lindenb** [comment]
:+1:

**Comment by mr-c** [comment]
Thanks for this! You will need to contact existing authors and get their
okay before merging. (or temporarily remove their contribution until they
respond). Otherwise :+1:

**Comment by tetron** [comment]
@portah can you comment then I can merge this?

**Comment by portah** [comment]
Sorry, yep, I'm agree. :+1:

**Pull request merged**
