### PR TITLE
Create sortSam.cwl

### PR DESCRIPTION
**Pull request by skanwal**
It belongs to picard toolkit

### CODE REVIEW

**Comment by portah** [comment]
The same problem with outputs/glob and OUTPUT= argument

**Comment by skanwal** [comment]
@portah changes incorporated

**Comment by portah** [comment]
SO= or SORT_ORDER= ?

**Comment by skanwal** [comment]
@portah it actually works with both prefixes.
Is it a way to add "or" in a prefix ?

**Pull request merged**
