### PR TITLE
Create realignTargetCreator.cwl

### PR DESCRIPTION
**Pull request by FarahZKhan**
To use it as stand alone tool - example: "cwltool realignerTargerCreator.cwl realignerTargerCreator.json". Still testing to make it work as a part of the workflow

### CODE REVIEW

**Comment by portah** [comment]
Repeatable arguments should not be hard copied also - it is good to use array 
```yaml
 - id: "#dbSNP"
    type: string
    default: "dbsnp_138.vcf"
    description: list of known variant files in vcf format
    inputBinding:
      position: 6
      prefix: "--known"

  - id: "#indelsMills"
    type: string
    default: "../data//GATK-complete-workflow/Ref_datasets/Mills_and_1000G_gold_st.vcf"
    description: list of known variant files in vcf format
    inputBinding:
      position: 7
      prefix: "--known"
    
  - id: "#indels1000G"
    type: string
    default: "../data//GATK-complete-workflow/Ref_datasets/1000G_phase1.indels.hg19.vcf"
    description: list of known variant files in vcf format
    inputBinding:
      position: 8
      prefix: "--known"

  - id: "#outputfile_realignTarget"
    type: string
    description: name of the output file from realignTargetCreator
    inputBinding:
      position: 9
      prefix: "-o"
        
outputs:
  - id: "#realignTargetCreator_output"
    type: "File"
    outputBinding: { glob: "realignTargetCreator_output.intervals" }
```

Hard copied output file name

**Comment by FarahZKhan** [comment]
@portah Done with the changes.

**Comment by portah** [comment]
There is an error in the file and job file please check

**Comment by FarahZKhan** [comment]
@portah I guess now the tool file is fixed.

**Comment by FarahZKhan** [comment]
reference.fai file and input.bam.bai file are required by GATK to process any bam file.

**Comment by portah** [comment]
I still confused by inputBinding: { position: 6, *prefix: "--known"* }

**Comment by FarahZKhan** [comment]
@portah yes that should just be position.

**Pull request merged**
