### PR TITLE
first try

### PR DESCRIPTION
**Pull request by lindenb**
Hi Peter,
thank your for your help. 

My current interest is to translate my  **Makefile**-based workflows to other engines. So my first idea is to just implement a **minimal** workflow, something like: 

```make
.PHONY: all
all: hello.txt
hello.txt:
	echo "Hello" > hello.txt
```

  * There is *no* input to my workflow (should I always specify a json ? does the name of the json matters ? is a dot in an 'id' means it's a key of a json object ?)
  * There is "no" declared output  (how to specify 'constant' Files ?)

my attempt so far:

```groovy
#!/usr/bin/env cwl-runner

- id: "#echocmd"
  class: CommandLineTool
  inputs:
    - id: "#echo-in"
      type: string
      label: "Message"
      description: "The message to print"
      default: "Hello World"
  outputs:
    - id: "#echo-out"
      type: File
      label: "Printed Message"
      description: "The file containing the message"
      outputBinding:
        glob: messageout.txt
  baseCommand: echo
  stdout: messageout.txt

- id: "#main"
  class: Workflow
  label: "Hello World"
  description: "Puts a message into a file using echo"
  inputs: []
  outputs:
    - id: "#main.output"
      type: File
      source: "#param.output"
  steps :
    - id: "#step0"
      run: {import: "#echocmd"}
      inputs: []
      outputs:
        - { id: "#main.output" }
```
(well I tried a few variations of this, without success...) The specification is quite large, and honestly, I didn't read/understand the whole document.

How can I make it run please ? :-)

Of course, don't accept this pull request for now. :-)

 
While I'm here:

* can I specify a whole bash line in a CommandLineTool ? something like :

```
   shell: /bin/bash
    baseCommand: " echo \"A'\  | tr 'A' B' | grep B "
```

Thank you for your help,

Pierre

### CODE REVIEW

**Comment by tetron** [comment]
You are pretty close, just a few changes:

* You need to put `inputBinding: {}` on the `#echo-in` parameter to indicate you want it added to the command line.
* The output parameter of `#step0` should be named `#step0.echo-out` (this is formed from the id of the step and name of the output parameter).
* Correspondingly the workflow output should be connected to the step output with `source: #step0.echo-out`

Here's the fixed up version:

```
#!/usr/bin/env cwl-runner

- id: "#echocmd"
  class: CommandLineTool
  inputs:
    - id: "#echo-in"
      type: string
      label: "Message"
      description: "The message to print"
      default: "Hello World"
      inputBinding: {}
  outputs:
    - id: "#echo-out"
      type: File
      label: "Printed Message"
      description: "The file containing the message"
      outputBinding:
        glob: messageout.txt
  baseCommand: echo
  stdout: messageout.txt

- id: "#main"
  class: Workflow
  label: "Hello World"
  description: "Puts a message into a file using echo"
  inputs: []
  outputs:
    - id: "#main.output"
      type: File
      source: "#echocmd.echo-out"
  steps :
    - id: "#step0"
      run: {import: "#echocmd"}
      inputs: []
      outputs:
        - { id: "#echocmd.echo-out" }
```

**Comment by lindenb** [comment]
:+1:  thanks; I'll update the code on monday

**Comment by lindenb** [comment]
OK, I've updated my cwl, It's working now , thanks ! :-)

**Comment by lindenb** [comment]
10H23: added a second example hello-param.cwl with parameters.

**Comment by mr-c** [comment]
I like this. @lindenb do you mind if I merge it in?

**Comment by lindenb** [comment]
@mr-c yes, you can merge :-)

I've got some other questions/test-cases. I'll ask for help in another pull-request.

Thanks

**Comment by mr-c** [comment]
My pleasure!

**Pull request merged**
