### PR TITLE
BWA tools aln/mem

### PR DESCRIPTION
**Pull request by portah**

### CODE REVIEW

**Comment by mr-c** [comment]
Ping @samuell :-)

**Comment by samuell** [comment]
@portah @mr-c Awesome! :)

[My bwa warp](https://github.com/BILS/workflows/commit/73198f60a1b993a2dbff426396647710e14fa60b) was a good practice though :)

**Comment by samuell** [comment]
@portah @mr-c Let me know if you wrap any more of the following tools, which are included in the test workflow I'll be testing out: https://github.com/BILS/cwl-evaluation/tree/master/002-resequencing#tools-included

**Comment by mr-c** [comment]
All of them? :-) Please send PRs until everything you need is in the
community repo.

On Thu, May 5, 2016 at 4:26 PM, Samuel Lampa <notifications@github.com>
wrote:

> @portah <https://github.com/portah> @mr-c <https://github.com/mr-c> Let
> me know if you wrap any more of the following tools, which are included in
> the test workflow I'll be testing out:
> https://github.com/BILS/cwl-evaluation/tree/master/002-resequencing#tools-included
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/common-workflow-language/workflows/pull/79#issuecomment-217168593>
>



-- 
Michael R. Crusoe                          michael.crusoe@gmail.com
Community Engineer                 Common Workflow Language project
*https://impactstory.org/u/0000-0002-2961-9670
<https://impactstory.org/u/0000-0002-2961-9670>*   +32 (0) 2 808 25 52
                                                    +1 480 627 9108

**Pull request merged**
